# Generated by Django 3.0.6 on 2020-05-11 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200511_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='static/media')),
                ('entries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Entries')),
            ],
        ),
    ]
